### ISSUE TITLE
many errors 

### ISSUE THREAD

**Issue by titu3e** [saintly2k/FoOlSlideX#12]
the errors happen in includes

**Comment by totavok8** [comment]
here he is ->  /includes/config.inc.php

**Comment by totavok8** [comment]
Specify exactly what errors and attach screenshots

**Comment by saintly2k** [comment]
also, this project is currently on hiatus, means i won't be working on it for a while. but i can help troubleshoot

**Comment by saintly2k** [comment]
Hello, @titu3e ? Will you ever tell me the errors?

**Comment by saintly2k** [comment]
never replied, open a new issue if you still need help.
