### ISSUE TITLE
add funcions

### ISSUE THREAD

**Issue by totavok8** [saintly2k/FoOlSlideX#19]
- Display the ability to change the site configuration from the admin panel, perhaps in this case some points will have to be transferred either to a json file that will be rewritten or entered into the database.
- make it possible to add users to groups with different privileges
admin, moderation, releaser, subscriber
> All features / the ability to check releases for moderation / the ability to post manga / the ability to read manga being only in a group

**Comment by totavok8** [comment]
Ability to add categories for both blogs or news + adding them to the menu.
Ability to create static pages with their content: title + description (example about us page)

**Comment by saintly2k** [comment]
I will think about those! Thanks!!

**Comment by saintly2k** [comment]
Also, I think that the normal user does not need an account since he can already do all the stuff that you *would* need an account for (bookmarking, etc). I think I won't add a feature for that.

**Comment by totavok8** [comment]
It would be nice to be able to maintain a separate template from the main one, which can be completely redone, not just change just css

**Comment by saintly2k** [comment]
this will be veeeeeeery hard, but i will try to maybe implement that in v0.2.x or so

**Comment by kaligula-eu** [comment]
customizing the menu is done ^^

**Comment by saintly2k** [comment]
news are done ^^
