### ISSUE TITLE
searching for translators

### ISSUE THREAD

**Issue by kaligula-eu** [saintly2k/FoOlSlideX#37]
if you want to contribute to FoOlSlideX but you cannot code? no problem! just help out by translating it into your language or update/improve a current language file ^^ just fork this repository, copy the contents of "lang/en.lang.php" to your new language file "language.lang.php" where "language" is the abbreviation of your language (like en for english, ru for russian, pt for portuguese, etc). if you're done, just upload and create a pull request :) 
thanks!!

**Comment by Okabetv** [comment]
Hi, I would like to contribute to the translation of the project by adding the Italian language
