### ISSUE TITLE
Оно живое ?

### ISSUE THREAD

**Issue by veopot** [saintly2k/FoOlSlideX#52]

**Comment by totavok8** [comment]
Более чем, было. У ребят ведь ковид и всякие сложности вот и затягивается процесс, обещали вроде выложить новую документацию после выхода новой версии, пока вот ей нет.
Ждём её, как появится переведу на ру, как и предыдущую версию.

**Comment by veopot** [comment]
Я уже думал ковид кончился

**Comment by saintly2k** [comment]
Ну, да, у меня был Ковид один раз мор несколько месяцев назад, но это было ничего серьезного. Я просто страдал от упадка сил из-за слабости организма и депрессии, поэтому не добился большого прогресса ни в одном проекте из-за отсутствия мотивации. Я постараюсь немного больше работать над этим и некоторыми другими проектами, так как мое восстановление идет хорошо :)

**Comment by veopot** [comment]
О я вас понимаю сам перенес ковид в 2022
На неделю скосило 
А в первые 2 дня встать не мог
